### ISSUE TITLE
Start denied to Schedule Controller 

### ISSUE THREAD

**Issue by PolynomialDivision** [twitchtv/acm-mmsys-2020-grand-challenge#8]
I'm facing nearly all the time this error:
> [415][ScheduleController][video] Start denied to Schedule Controller 

Sometimes streaming works. Any ideas?

Platform:
- Manjaro
- Own FFmpeg build

**Comment by johnBartos** [comment]
Hi @PolynomialDivision, sorry for the late reply. I haven't seen it before, and the linked Dash.js issue seems to indicate that the player has an issue with very small segments (< 0.1s) Unfortunately the challenge requires segments that small. Since we're pretty late in the game here it is probably best to try a different OS or distro.
